<a href="https://colab.research.google.com/github/PurpleCoder-23/Deep-learning/blob/main/TenorFlow_Tensors_%26_casting_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np


In [ ]:
tensor_zero_d=tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d=tf.constant([2,0,-3])
print(tensor_one_d)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [ ]:
tensor_two_d=tf.constant([
                          [1,2,0],
                          [3,5,-2],
                          [1,5,6],
                          [2,3,8]

                          ])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -2]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [ ]:
tensor_three_d=tf.constant([

  [[ 1,  2,  0],
  [ 3 , 5, -1]],

 [[10 , 2,  0],
  [ 1 , 0  ,2]],

 [[ 5,  8,  0],
  [ 2 , 7,  0]],

 [[ 2,  1 , 9],
  [ 4, -3 ,32]],
])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
print(tensor_three_d.shape)

(4, 2, 3)


In [ ]:
print(tensor_three_d.ndim)

3


In [ ]:
tensor_four_d=tf.constant([


  [
   [[ 1,  2,  0],
  [ 3 , 5, -1]],

 [[10 , 2,  0],
  [ 1 , 0  ,2]],

 [[ 5,  8,  0],
  [ 2 , 7,  0]],

 [[ 2,  1 , 9],
  [ 4, -3 ,32]],
],
  [
   [[ 1,  2,  0],
  [ 3 , 5, -1]],

 [[10 , 2,  0],
  [ 1 , 0  ,2]],

 [[ 5,  8,  0],
  [ 2 , 7,  0]],

 [[ 2,  1 , 9],
  [ 4,-3,8] ]
  ],

 [
   [[ 1,  2,  0],
  [ 3 , 5, -1]],

 [[10 , 2,  0],
  [ 1 , 0  ,2]],

 [[ 5,  8,  0],
  [ 2 , 7,  0]],

 [[ 2,  1 , 9],
  [ 4,-3,8]]
 ]
])

print(tensor_four_d)

tf.Tensor(
[[[[ 1  2  0]
   [ 3  5 -1]]

  [[10  2  0]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  7  0]]

  [[ 2  1  9]
   [ 4 -3 32]]]


 [[[ 1  2  0]
   [ 3  5 -1]]

  [[10  2  0]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  7  0]]

  [[ 2  1  9]
   [ 4 -3  8]]]


 [[[ 1  2  0]
   [ 3  5 -1]]

  [[10  2  0]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  7  0]]

  [[ 2  1  9]
   [ 4 -3  8]]]], shape=(3, 4, 2, 3), dtype=int32)


In [ ]:
print(tensor_four_d.ndim)

4


In [ ]:
print(tensor_four_d.shape)

(3, 4, 2, 3)


In [ ]:
tensor_one_d=tf.constant([2,3,8.0,7],dtype=tf.float32)

casted_tensor_one_d=tf.cast(tensor_one_d,dtype=tf.int16)
print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([2. 3. 8. 7.], shape=(4,), dtype=float32)
tf.Tensor([2 3 8 7], shape=(4,), dtype=int16)


In [ ]:
tensor_bool=tf.constant([True,True,False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [ ]:
tensor_string=tf.constant(['Hello world','bye'])
print(tensor_string)

tf.Tensor([b'Hello world' b'bye'], shape=(2,), dtype=string)


In [ ]:
import numpy as np

In [ ]:
np_array=np.array([1,2,4])
print(np_array)

[1 2 4]


In [ ]:
converted_tensor=tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [ ]:
eye_tensor=tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
fill_tensor=tf.fill([2,3],5)
print(fill_tensor)

tf.Tensor(
[[5 5 5]
 [5 5 5]], shape=(2, 3), dtype=int32)


In [ ]:
ones_tensor=tf.ones(
    [5,3],
    dtype=tf.dtypes.float32,
    name=None
)
print(ones_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(5, 3), dtype=float32)


In [ ]:
ones_like_tensor=tf.ones_like(fill_tensor)
print(ones_like_tensor)

tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)


In [ ]:
print(tf.shape(tensor_three_d))

tf.Tensor([4 2 3], shape=(3,), dtype=int32)


In [ ]:
t=tf.constant([[1,1,1],[2,2,2]])
tf.rank(t)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
t=tf.constant([[[1,1,1],[2,2,2],[3,3,3]]])
tf.size(t)

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [ ]:
random_tensor=tf.random.normal(
    [3,2],
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[ 0.4141835  -1.2098222 ]
 [ 0.38470858 -0.27513453]
 [-1.0160352  -0.06939355]], shape=(3, 2), dtype=float32)


In [ ]:
random_tensor1=tf.random.uniform(
    [1,],
    minval=0,
    maxval=5,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor1)

tf.Tensor([1.9829935], shape=(1,), dtype=float32)


In [ ]:
tensor_indexed=tf.constant([3,5,2,4,6,66,7])
print(tensor_indexed)
print(tensor_indexed[0:4])
print(tensor_indexed[1:5])

tf.Tensor([ 3  5  2  4  6 66  7], shape=(7,), dtype=int32)
tf.Tensor([3 5 2 4], shape=(4,), dtype=int32)
tf.Tensor([5 2 4 6], shape=(4,), dtype=int32)


In [ ]:
tf.range(2,5)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4], dtype=int32)>

In [ ]:
tensor_two_d=tf.constant([
                          [1,2,0],
                          [3,5,-2],
                          [1,5,6],
                          [2,3,8]

                          ])
print(tensor_two_d[0:3 , 0:2])

tf.Tensor(
[[1 2]
 [3 5]
 [1 5]], shape=(3, 2), dtype=int32)


In [ ]:
tensor_three_d=tf.constant([

  [[ 1,  2,  0],
  [ 3 , 5, -1]],

 [[10 , 2,  0],
  [ 1 , 0  ,2]],

 [[ 5,  8,  0],
  [ 2 , 7,  0]],

 [[ 2,  1 , 9],
  [ 4, -3 ,32]],
])
print(tensor_three_d[0:2 ,:, :])

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]], shape=(2, 2, 3), dtype=int32)


In [ ]:
x_abs=tf.constant([-2.25,3.25])
tf.abs(x_abs)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [ ]:
x_abs_complec=tf.constant([-2.25+4.75j])
tf.abs(x_abs_complec)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([5.25594901])>

In [ ]:
tf.sqrt((-2.25)**2+4.75**2)

<tf.Tensor: shape=(), dtype=float32, numpy=5.255949>

In [ ]:
x_1=tf.constant([5,3,6,6,4,6], dtype=tf.int32)
x_2=tf.constant([7,6,2,6,7,11], dtype=tf.int32)

print(tf.add(x_1,x_2))

tf.Tensor([12  9  8 12 11 17], shape=(6,), dtype=int32)


In [ ]:
x_1=tf.constant([5,3,6,6,4,6], dtype=tf.int32)
x_2=tf.constant([7], dtype=tf.int32)

print(tf.math.add(x_1,x_2))

tf.Tensor([12 10 13 13 11 13], shape=(6,), dtype=int32)


In [ ]:
x_1=tf.constant([[5,3,6,6,4,6],], dtype=tf.float32)
x_2=tf.constant([[7],[5],[3]],dtype=tf.float32)

print(x_1.shape)
print(x_2.shape)
print(tf.math.multiply(x_1,x_2))

(1, 6)
(3, 1)
tf.Tensor(
[[35. 21. 42. 42. 28. 42.]
 [25. 15. 30. 30. 20. 30.]
 [15.  9. 18. 18. 12. 18.]], shape=(3, 6), dtype=float32)


In [ ]:
x_argmax=tf.constant([200,120,130,3,6])
print(tf.math.argmax(x_argmax))

tf.Tensor(0, shape=(), dtype=int64)


In [ ]:
x_argmax=tf.constant([200,120,130,309,6])
print(tf.math.argmax(x_argmax))

tf.Tensor(3, shape=(), dtype=int64)


In [ ]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[3, 0], [2, 1]])
tf.pow(x, y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[8, 1],
       [9, 3]], dtype=int32)>

In [ ]:
tf.pow(tf.constant(2),tf.constant(3))

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [ ]:
tensor_two_d=tf.constant([
                          [1,2,0],
                          [3,5,-2],
                          [1,5,6],
                          [2,3,8]

                          ])



print(tf.math.reduce_sum(
    tensor_two_d, axis=None, keepdims=False, name=None)
)

tf.Tensor(34, shape=(), dtype=int32)


In [ ]:
tf.math.top_k(tensor_two_d, k=1)

TopKV2(values=<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[2],
       [5],
       [6],
       [8]], dtype=int32)>, indices=<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[1],
       [1],
       [2],
       [2]], dtype=int32)>)

In [ ]:
x_1=tf.constant([[1,2,0],
                 [3,5,-1]])
x_2=tf.constant([[1,2,0],
                 [3,5,-1],
                 [4,8,2]])


tf.linalg.matmul(
    x_1,
    x_2,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    name=None
)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7, 12, -2],
       [14, 23, -7]], dtype=int32)>

In [ ]:
tf.transpose(x_1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  3],
       [ 2,  5],
       [ 0, -1]], dtype=int32)>

In [ ]:
print(x_1)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]], shape=(2, 3), dtype=int32)


In [ ]:
tensor_three_d=tf.constant([

  [[ 1,  2,  0],
  [ 3 , 5, -1]],

 [[10 , 2,  0],
  [ 1 , 0  ,2]],

 [[ 5,  8,  0],
  [ 2 , 7,  0]],

 [[ 2,  1 , 9],
  [ 4, -3 ,32]],
])
print(tensor_three_d)



In [ ]:
tensor_three_d=tf.constant([

  [[ 1,  2,  0],
  [ 3 , 5, -1]],

 [[10 , 2,  0],
  [ 1 , 0  ,2]],

 [[ 5,  8,  0],
  [ 2 , 7,  0]],

 [[ 2,  1 , 9],
  [ 4, -3 ,32]],
])




print(tensor_three_d)

In [ ]:
tensor_three_d=tf.constant([

  [[ 1,  2,  0],
  [ 3 , 5, -1]],

 [[10 , 2,  0],
  [ 1 , 0  ,2]],

 [[ 5,  8,  0],
  [ 2 , 7,  0]],

 [[ 2,  1 , 9],
  [ 4, -3 ,32]],
])












print(tensor_three_d)

In [ ]:
tensor_three_d=tf.constant([

  [[ 1,  2,  0],
  [ 3 , 5, -1]],

 [[10 , 2,  0],
  [ 1 , 0  ,2]],

 [[ 5,  8,  0],
  [ 2 , 7,  0]],

 [[ 2,  1 , 9],
  [ 4, -3 ,32]],
])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
x_1@x_2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7, 12, -2],
       [14, 23, -7]], dtype=int32)>

In [ ]:
tf.linalg.inv(tensor_two_d)

InvalidArgumentError: ignored

In [ ]:
import numpy as np

In [ ]:
A=np.array([[2,6,5,2],
           [2,2,2,3],
           [1,5,4,0]])

B=np.array([[2,9,0,3,0],
            [3,6,8,-2,2],
            [3,3,5,0,1],
            [3,0,2,0,5]])

print(A.shape)
print(B.shape)
print(np.matmul(A,B))


#Einsum oprator
print('Einsum C=: \n')
print(np.einsum("ij,jk->ik",A,B))

(3, 4)
(4, 5)
[[43 69 77 -6 27]
 [25 36 32  2 21]
 [29 51 60 -7 14]]
Einsum C=: 

[[43 69 77 -6 27]
 [25 36 32  2 21]
 [29 51 60 -7 14]]


In [ ]:
A=np.array([[2,6,5,2],
           [2,2,2,3],
           [1,5,4,0]])

print("Transpose A=: \n")
print(A.T)



print('Einsum Transpose A=: \n')
print(np.einsum('ij->ji'),A)

Transpose A=: 

[[2 2 1]
 [6 2 5]
 [5 2 4]
 [2 3 0]]
Einsum Transpose A=: 



ValueError: ignored

In [ ]:
A=np.array([
    [[2,6,5,2],
     [2,-2,2,3],
     [1,5,4,0]],

    [[1,3,1,22],
     [0,2,2,0],
     [1,5,4,1]]
])

B=np.array([
    [[2,9,0,3,0],
     [3,6,8,-2,2],
     [1,3,5,0,1],
     [3,0,2,0,5]],

    [[1,0,0,3,0],
     [3,0,4,-2,2],
     [1,0,2,0,0],
     [3,0,1,1,0]]
])


print(A.shape)
print(B.shape)

print("batch multiplication C=: \n")
print(np.matmul(A,B),'\n')


print("Einsum C=: \n")
print(np.einsum('bij,bjk->bik',A,B))

(2, 3, 4)
(2, 4, 5)
batch multiplication C=: 

[[[33 69 77 -6 27]
  [ 9 12  0 10 13]
  [21 51 60 -7 14]]

 [[77  0 36 19  6]
  [ 8  0 12 -4  4]
  [23  0 29 -6 10]]] 

Einsum C=: 

[[[33 69 77 -6 27]
  [ 9 12  0 10 13]
  [21 51 60 -7 14]]

 [[77  0 36 19  6]
  [ 8  0 12 -4  4]
  [23  0 29 -6 10]]]


In [ ]:
A=np.array([
    [[2,6,5,2],
     [2,-2,2,3],
     [1,5,4,0]],

    [[1,3,1,22],
     [0,2,2,0],
     [1,5,4,1]]
])

print("Sum A=: \n")
print(np.sum(A),"\n")

print("Einsum A =: \n")
print(np.einsum("bij->",A))

Sum A=: 

72 

Einsum A =: 

72


In [ ]:
Q=batchsize,s_q,modelsize
K=batchsize,s_k,modelsize

Q=np.random.randn(32,64,512)bqm
K=np.random.randn(32,128,512)nkm



NameError: ignored

In [ ]:
np.einsum("bqm,bkm->bqk",Q,K).shape

NameError: ignored

In [ ]:
A=np.random.randn(2,4,4,2)#bcij
B=np.random.randn(2,4,4,1)#bcik

In [ ]:
np.einsum("bcik,bcij->bckj",B,A)

array([[[[ 2.10699773,  1.54971428]],

        [[-0.60564602,  2.28091723]],

        [[-3.51073293,  2.03893364]],

        [[ 1.22366517, -0.14894804]]],


       [[[-0.8691112 ,  0.54566275]],

        [[-1.41177834,  0.81098067]],

        [[-1.72659116,  0.19335442]],

        [[-1.29693415, -2.8583558 ]]]])

In [ ]:
np.matmul(np.transpose(0,(0,1,2,4,3)),A).shape

ValueError: ignored

In [ ]:
#expand_dims

x=tf.constant([[[2,3,4,5]]])
print(x.shape)
x_expanded=tf.expand_dims(x,axis=0)
print(x_expanded)

(1, 1, 4)
tf.Tensor([[[[2 3 4 5]]]], shape=(1, 1, 1, 4), dtype=int32)


In [ ]:
#tf.squeeze

x_squeezed=tf.squeeze(x_expanded, axis=0)

for i in range(2):
  x_squeezed=tf.squeeze(x_squeezed,axis=0)


print(x_squeezed)



tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)


In [ ]:
#tf.reshape

x_reshape=tf.constant([[3,5,6,6],
                       [4,6,-1,2]])

tf.reshape(x_reshape,[4,2])

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 3,  5],
       [ 6,  6],
       [ 4,  6],
       [-1,  2]], dtype=int32)>

In [ ]:
t1 = [[1, 2, 3],
      [4, 5, 6]]


t2 = [[7, 8, 9],
      [10, 11, 12]]

print(tf.constant(t1).shape)
print(tf.constant(t2).shape)


tf.concat([t1, t2], 0)

(2, 3)
(2, 3)


<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
#tf.stack
tf.stack([t1,t2], axis=1)

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 7,  8,  9]],

       [[ 4,  5,  6],
        [10, 11, 12]]], dtype=int32)>

In [ ]:
tf.concat([tf.expand_dims(t, axis=0) for t in [t1,t2]],axis=0)

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [ ]:
t = tf.constant([[1, 2, 3],
                 [4, 5, 6]])

paddings = tf.constant([[1, 1,],
                        [2, 2]])

# 'constant_values' is 0.

tf.pad(t,paddings,'CONSTANT',constant_values=3)

<tf.Tensor: shape=(4, 7), dtype=int32, numpy=
array([[3, 3, 3, 3, 3, 3, 3],
       [3, 3, 1, 2, 3, 3, 3],
       [3, 3, 4, 5, 6, 3, 3],
       [3, 3, 3, 3, 3, 3, 3]], dtype=int32)>

In [ ]:
#tf.gather
params=tf.constant(['p0','p1','p2','p3','p4','p5'])
params[1:3+1]

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>

In [ ]:
tf.gather(params,[1,2,3])

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>

In [ ]:
params=tf.constant([[0,1.0,2.0],
                   [10.0,11.0,12.0],
                   [20.0,21.0,22.0],
                   [30.0,31.0,32.0]])

print(params.shape)
tf.gather(params,[0,3],axis=0)

(4, 3)


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.,  1.,  2.],
       [30., 31., 32.]], dtype=float32)>

In [ ]:
indices=[2,1]
params=[['a','b'],
        ['c','d'],
        ['e','f']]

tf.gather_nd(params,indices)


<tf.Tensor: shape=(), dtype=string, numpy=b'f'>

In [ ]:
indices=[[0,1],[1,0]]

params=[[['a0','b0'],
         ['c0','d0']],

        [['a1','b1'],
         ['c1','d1']]]

tf.gather_nd(params,indices)

<tf.Tensor: shape=(2, 2), dtype=string, numpy=
array([[b'c0', b'd0'],
       [b'a1', b'b1']], dtype=object)>

In [ ]:
#tf.ragged
tensor_two_d=[[1,2,0],
              [3,],
              [1,5,6],
              [2,3,8]]

tensor_ragged=tf.ragged.constant(tensor_two_d)
print(tensor_ragged.shape)

(4, None)


In [ ]:
#tf.raggedTensor

print(tf.RaggedTensor.from_row_lengths(
    values=[3,1,4,1,5,9,2,6],
    row_lengths=[4,0,3,1,0]
))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


In [ ]:
tensor_sparse=tf.sparse.SparseTensor(
    indices=[[1,1],[3,4]], values=[11,56], dense_shape=[5,6]
)

In [ ]:
print(tensor_sparse)

SparseTensor(indices=tf.Tensor(
[[1 1]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([11 56], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))


In [ ]:
tf.sparse.to_dense(tensor_sparse)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 56,  0],
       [ 0,  0,  0,  0,  0,  0]], dtype=int32)>

In [ ]:
tf.sparse.to_dense(tensor_sparse)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 56,  0],
       [ 0,  0,  0,  0,  0,  0]], dtype=int32)>

In [ ]:
tensor_string=tf.constant(['hello','i am','a string'])
print(tensor_string)

tf.Tensor([b'hello' b'i am' b'a string'], shape=(3,), dtype=string)


In [ ]:
tf.strings.join(
    tensor_string, separator='+', name=None
)

<tf.Tensor: shape=(), dtype=string, numpy=b'hello+i am+a string'>

In [ ]:
x=tf.constant([1,2])


In [ ]:
x_var=tf.Variable(x,name='var1')
print(x_var)

<tf.Variable 'var1:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>


In [ ]:
x_var.assign_add([5,8])


<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([ 6, 10], dtype=int32)>

In [ ]:
with tf.device('CPU:0'):
  x_var=tf.constant([1,3,4])
  x_2=tf.constant([1])

  with tf.device('GPU:0'):

    x_3=x_1+x_2

  print(x_1,x_1.device)

  print(x_2,x_2.device)
  print(x_3,x_3.device)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]], shape=(2, 3), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([1], shape=(1,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor(
[[2 3 1]
 [4 6 0]], shape=(2, 3), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
